Feature/prasolova tests
reurairin/ML_2S_Final pull request #8
Opened 2023-04-27 18:45 UTC by Zhenya127

2023-04-27 19:17 UTC, reurairin requested changes

2023-04-27 19:17 UTC, reurairin commented on .gitignore
> -dist/
Please don't remove this folder for the sake of endpoint test. Compiled files should not be pushed to the repo

2023-04-28 18:12 UTC, pyretttt approved these changes

2023-04-28 18:50 UTC, reurairin approved these changes

2023-04-28 18:52 UTC, merged